### ISSUE TITLE
This container has its own installation of consul?

### ISSUE THREAD

**Issue by CodisRedding** [autopilotpattern/mysql#70]
This container has its own installation of consul? Can someone help me understand why it would have its own oppose to linking to an existing consul container in my docker-compose.yml?

I have a few services listed in my local docker-compose, one of them being consul, as to use autopilot to communicate. Each of our services have their own mysql db. I’m trying to understand how to best use a mysql container for each. I figured I would spin up a mysql image and point to a data volume on the host, and point to the existing consul container but this mysql container doesn’t seem to be for that use-case unless I’m thinking about it wrong?

**Comment by tgross** [comment]
Your question is a little unclear... are you asking about why this example has its own Consul or why there's a Consul agent running inside the container?

If you're asking why this example has its own Consul:

We've provided [Consul in the docker-compose.yml](https://github.com/autopilotpattern/mysql/blob/93fdf1ba0ed16cefd4bbf5e102ce3586229b6efe/docker-compose.yml#L17-L39) because without it we couldn't stand this stack up as a standalone example. For your own use you'll want to have a shared Consul cluster that can be used by all your applications so that they can share the service discovery data. For example of how you might use this MySQL image is used in a full application stack, check out our [WordPress example](https://github.com/autopilotpattern/wordpress/blob/master/docker-compose.yml).

If you're asking why there's a Consul agent running inside the container:

We're assuming in this example that we're running on Triton. In some other environments you'd have a "host-local" Consul Agent on each host where you're running containers. This Consul Agent will talk to the Consul server cluster. But on Triton (or any PaaS or CaaS environment), you don't have the notion of host local services, so instead we [run the Consul Agent as a co-process](https://github.com/autopilotpattern/mysql/blob/93fdf1ba0ed16cefd4bbf5e102ce3586229b6efe/etc/containerpilot.json#L33-L41) within the container. The Consul Agent is what gossips configuration with the [Consul server cluster](https://github.com/autopilotpattern/mysql/blob/93fdf1ba0ed16cefd4bbf5e102ce3586229b6efe/docker-compose.yml#L17-L39). If you want to dive into the design details of that, you might want to check out the extended discussion in https://github.com/joyent/containerpilot/issues/162 and https://github.com/joyent/containerpilot/issues/175

**Comment by CodisRedding** [comment]
Wonderful, that's exactly what I was looking for. ty
